# User options are in src/include/makefile.inc
# This Makefile is designed for gnu make version 3.75 or newer
# Please report problems to lapsbugs@fsl.noaa.gov
#
#

#=============================================================
#  LAPS environment:
#=============================================================

SRCROOT=../../..

include $(SRCROOT)/src/include/makefile.inc

RM = rm -f
FLAG = $(FFLAGS)

LAPSLIBS = $(SRCROOT)/src/lib/wind/libwind.a \
           $(SRCROOT)/src/wind/libwind.a \
	   $(SRCROOT)/src/balance/libqbalpe.a \
           $(SRCROOT)/src/lib/temp/libtemp.a \
           $(SRCROOT)/src/lib/liblaps.a  \
           $(SRCROOT)/src/lib/modules/libmodules.a  \
           $(SRCROOT)/src/lib/mthermo/libmthermo.a  \
           $(SRCROOT)/src/lib/util/libutil.a  \
           $(SRCROOT)/src/lib/goeslib/libgoeslib.a \
	   $(SRCROOT)/src/lib/radar/moving/libairad.a \
	   $(SRCROOT)/src/humid/liblq3.a

DBLAPSLIBS = $(SRCROOT)/src/lib/wind/libdebugwind.a \
	     $(SRCROOT)/src/balance/libqbalpe.a \
             $(SRCROOT)/src/lib/temp/libdebugtemp.a \
             $(SRCROOT)/src/lib/libdebuglaps.a  \
             $(SRCROOT)/src/lib/modules/libdebugmodules.a  \
             $(SRCROOT)/src/lib/mthermo/libdebugmthermo.a  \
             $(SRCROOT)/src/lib/util/libdebugutil.a  \
             $(SRCROOT)/src/lib/goeslib/libdebuggoeslib.a \
	     $(SRCROOT)/src/lib/radar/moving/libdebugairad.a \
	     $(SRCROOT)/src/humid/liblq3.a

#LAPSFC = $(SRCROOT)/src/sfc/libsfc.a

BUFRLIB = $(SRCROOT)/src/var/bufr/libbufr.a

#WINDLIB = $(SRCROOT)/src/wind/libwind.a

#HUMIDLIB = $(SRCROOT)/src/humid/liblq3.a

INCXIE=-I.. -I../observations
LIBXIE=-L..

.SUFFIXES:
.SUFFIXES: .o .c .f90 .a .f
.f90.o:;    $(FC) $(FLAG) $(FREE) -c $*.f90
.f.o:;      $(FC) $(FLAG) -c $*.f
.c.o:;	    $(CC) $(CPPFLAGS) -c $*.c

#=============================================================
# STMAS_4D:
#=============================================================

ANA = drv

STMAS= \
      mapping.f90 \
      insitu_map.f90 \
      drv.f90

all: $(ANA) 

$(ANA): $(STMAS) $(LAPSLIBS)
	$(FC) $(FFLAGS) $(FREE) $(INCXIE) $(STMAS) $(LAPSFC) $(LAPSLIBS) \
	$(BUFRLIB) $(OTHERLIBS) -o $@ $(LIBXIE) -lstmas4d
	rm -f *.o

debug: $(STMAS) #$(STMAS_CG)
	$(RM) $(ANA) $(ANA_CG);
	$(MAKE) LAPSLIBS='$(DBLAPSLIBS) $(BUFRLIB)' \
	CFLAGS='$(DBCFLAGS)' FFLAGS='$(DBFLAGS)'

install: $(ANA) # $(ANA_CG): compilation problem for cg_descent.f on toro.
	$(INSTALL) $(ANA) $(INSTALLROOT)/bin/$(ANA)
#	$(INSTALL) $(ANA_CG) $(INSTALLROOT)/bin/$(ANA_CG)

clean:
	rm -f $(ANA) $(ANA_CG) $(POST)  *.o *~ *# *.mod

distclean: clean

